/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2018-03-21T23:36:31.051+01:00
  3.16.0.2
  
  Standalone prediction code with sample test data for KMeansModel named kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://10.1.3.192:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://10.1.3.192:54321/3/Models.java/kmeans-26607a20-9e61-407b-bb37-7f529ec5d76d > kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;
import hex.genmodel.IClusteringModel;

@ModelPojo(name="kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d", algorithm="kmeans")
public class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d extends GenModel implements IClusteringModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Clustering; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* BABY_ARTIKELEN */ null,
    /* BELASTINGEN */ null,
    /* ELEKTRONICA_WINKELS */ null,
    /* FAMILIELEDEN */ null,
    /* GOEDE_DOELEN */ null,
    /* HORECA */ null,
    /* HUUR */ null,
    /* HYPOTHEEKAFSCHRIJVINGEN */ null,
    /* LEESMATERIAAL */ null,
    /* MODEWINKELS */ null,
    /* NUTSBEDRIJVEN */ null,
    /* SPAREN */ null,
    /* SPORT_ARTIKELEN */ null,
    /* SUPERMARKTEN */ null,
    /* TANKEN */ null,
    /* TELECOMBEDRIJVEN */ null
  };

  public kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d() { super(NAMES,DOMAINS,null); }
  public String getUUID() { return Long.toString(504873017842791536L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    Kmeans_preprocessData(data,kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MEANS.VALUES,kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MULTS.VALUES,kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MODES.VALUES);
    preds[0] = KMeans_closest(kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS.VALUES, data, DOMAINS); 
    return preds;
  }

  // Pass in data in a double[], in a same way as to the score0 function.
  // Cluster distances will be stored into the distances[] array. Function
  // will return the closest cluster. This way the caller can avoid to call
  // score0(..) to retrieve the cluster where the data point belongs.
  public final int distances( double[] data, double[] distances ) {
    Kmeans_preprocessData(data,kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MEANS.VALUES,kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MULTS.VALUES,kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MODES.VALUES);
    int cluster = KMeans_distances(kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS.VALUES, data, DOMAINS, distances); 
    return cluster;
  }

  // Returns number of cluster used by this model.
  public final int getNumClusters() {
    int nclusters = kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS.VALUES.length;
    return nclusters;
  }
}
// The class representing training column names
class NamesHolder_kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d implements java.io.Serializable {
  public static final String[] VALUES = new String[16];
  static {
    NamesHolder_kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_0.fill(VALUES);
  }
  static final class NamesHolder_kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "BABY_ARTIKELEN";
      sa[1] = "BELASTINGEN";
      sa[2] = "ELEKTRONICA_WINKELS";
      sa[3] = "FAMILIELEDEN";
      sa[4] = "GOEDE_DOELEN";
      sa[5] = "HORECA";
      sa[6] = "HUUR";
      sa[7] = "HYPOTHEEKAFSCHRIJVINGEN";
      sa[8] = "LEESMATERIAAL";
      sa[9] = "MODEWINKELS";
      sa[10] = "NUTSBEDRIJVEN";
      sa[11] = "SPAREN";
      sa[12] = "SPORT_ARTIKELEN";
      sa[13] = "SUPERMARKTEN";
      sa[14] = "TANKEN";
      sa[15] = "TELECOMBEDRIJVEN";
    }
  }
}
// Column means of training data
class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MEANS implements java.io.Serializable {
  public static final double[] VALUES = new double[16];
  static {
    kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MEANS_0.fill(VALUES);
  }
  static final class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MEANS_0 implements java.io.Serializable {
    static final void fill(double[] sa) {
      sa[0] = 1046.3009999999997;
      sa[1] = 302168.7201999998;
      sa[2] = 37566.24999999999;
      sa[3] = 32418.991799999996;
      sa[4] = 147.78249999999997;
      sa[5] = 1355.7687000000003;
      sa[6] = 10886.9967;
      sa[7] = 9654.824499999997;
      sa[8] = 121.65099999999998;
      sa[9] = 30215.482099999994;
      sa[10] = 931.7821999999999;
      sa[11] = 2965.4817999999987;
      sa[12] = 679.3291999999999;
      sa[13] = 3213.1558999999997;
      sa[14] = 699.1039;
      sa[15] = 269.8364000000002;
    }
  }
}
// Reciprocal of column standard deviations of training data
class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MULTS implements java.io.Serializable {
  public static final double[] VALUES = new double[16];
  static {
    kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MULTS_0.fill(VALUES);
  }
  static final class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MULTS_0 implements java.io.Serializable {
    static final void fill(double[] sa) {
      sa[0] = 9.81633893815109E-4;
      sa[1] = 3.222786441521775E-6;
      sa[2] = 2.2010000495399766E-5;
      sa[3] = 2.81615167202177E-5;
      sa[4] = 0.006534166837396137;
      sa[5] = 7.525065061107547E-4;
      sa[6] = 8.205251775296399E-5;
      sa[7] = 9.356637204138308E-5;
      sa[8] = 0.007354922377528845;
      sa[9] = 3.333457855910122E-5;
      sa[10] = 9.277748451251877E-4;
      sa[11] = 3.069971031621734E-4;
      sa[12] = 0.001504826525934068;
      sa[13] = 3.1483959282907665E-4;
      sa[14] = 0.0013764514333066457;
      sa[15] = 0.003408014821004887;
    }
  }
}
// Mode for categorical columns
class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MODES implements java.io.Serializable {
  public static final int[] VALUES = new int[16];
  static {
    kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MODES_0.fill(VALUES);
  }
  static final class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_MODES_0 implements java.io.Serializable {
    static final void fill(int[] sa) {
      sa[0] = -1;
      sa[1] = -1;
      sa[2] = -1;
      sa[3] = -1;
      sa[4] = -1;
      sa[5] = -1;
      sa[6] = -1;
      sa[7] = -1;
      sa[8] = -1;
      sa[9] = -1;
      sa[10] = -1;
      sa[11] = -1;
      sa[12] = -1;
      sa[13] = -1;
      sa[14] = -1;
      sa[15] = -1;
    }
  }
}
// Normalized cluster centers[K][features]
class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS implements java.io.Serializable {
  public static final double[][] VALUES = new double[5][];
  static {
    kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0.fill(VALUES);
  }
  static class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_0 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_0_0.fill(VALUES);
    }
    static final class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_0_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = 0.32213333555214596;
        sa[1] = -0.0739303480628195;
        sa[2] = -0.2760235644627216;
        sa[3] = -0.2947844263588506;
        sa[4] = 0.5430768814247571;
        sa[5] = -0.19307269445008546;
        sa[6] = -0.3539192037362866;
        sa[7] = 1.1737244324008933;
        sa[8] = -0.5041103915316691;
        sa[9] = -0.3678768121772143;
        sa[10] = -0.10283112263243194;
        sa[11] = 0.7923508771067915;
        sa[12] = -0.0027006437648879836;
        sa[13] = 0.004073740975574785;
        sa[14] = -0.1660742335890366;
        sa[15] = -0.1254677386607532;
      }
    }
}
  static class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_1 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_1_0.fill(VALUES);
    }
    static final class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_1_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.21782750593925387;
        sa[1] = -0.05104751985222733;
        sa[2] = -0.2693218824768805;
        sa[3] = 0.11718330119879375;
        sa[4] = -0.29942819532367776;
        sa[5] = 0.0031633868503881057;
        sa[6] = 0.5448772355334282;
        sa[7] = -0.46304271223716303;
        sa[8] = -0.15375832976342915;
        sa[9] = -0.3741639803700893;
        sa[10] = 0.1522912719477953;
        sa[11] = 0.05815836011522111;
        sa[12] = -0.34832701140284156;
        sa[13] = -0.34973055728182484;
        sa[14] = 1.2427224319488817;
        sa[15] = 0.871337714132264;
      }
    }
}
  static class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_2 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_2_0.fill(VALUES);
    }
    static final class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_2_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.4122880350644842;
        sa[1] = -0.17348642722188382;
        sa[2] = 2.3419902433800424;
        sa[3] = -0.45801994428143594;
        sa[4] = -0.08785731826782202;
        sa[5] = -0.10463630559375292;
        sa[6] = 0.011677027820536692;
        sa[7] = -0.30142363088824586;
        sa[8] = 0.4071121150817693;
        sa[9] = 0.2641535753343184;
        sa[10] = -0.10832980516718031;
        sa[11] = -0.47747596128302594;
        sa[12] = -0.3788112855563719;
        sa[13] = -0.10764000464898442;
        sa[14] = -0.4688270204305555;
        sa[15] = -0.5025307566396748;
      }
    }
}
  static class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_3 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_3_0.fill(VALUES);
    }
    static final class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_3_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = 0.001689738390277457;
        sa[1] = -0.16852626583598726;
        sa[2] = -0.3142478338613064;
        sa[3] = -0.13075125606461718;
        sa[4] = -0.10331382586122341;
        sa[5] = 1.0302408150410256;
        sa[6] = -0.1877368551692113;
        sa[7] = -0.21955182156016895;
        sa[8] = -0.4746161695193858;
        sa[9] = 1.5428823296578376;
        sa[10] = -0.00880989888435062;
        sa[11] = -0.21345563842344445;
        sa[12] = 0.11478848606739751;
        sa[13] = -0.34950825274932346;
        sa[14] = -0.3891897238322205;
        sa[15] = 0.1408815591222917;
      }
    }
}
  static class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_4 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_4_0.fill(VALUES);
    }
    static final class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_4_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = 0.07546026223368918;
        sa[1] = 0.2618690241483113;
        sa[2] = -0.38974874748968247;
        sa[3] = 0.40898627725498526;
        sa[4] = -0.10856912503504883;
        sa[5] = -0.41634919474752813;
        sa[6] = -0.0020662077393140198;
        sa[7] = -0.31764202520326024;
        sa[8] = 0.5982318865452981;
        sa[9] = -0.4766301045825706;
        sa[10] = 0.022971903517163193;
        sa[11] = -0.3184975555192735;
        sa[12] = 0.3317339846350031;
        sa[13] = 0.4875279033344887;
        sa[14] = -0.3089195155070486;
        sa[15] = -0.38038211922453913;
      }
    }
}
  static final class kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0 implements java.io.Serializable {
    static final void fill(double[][] sa) {
      sa[0] = kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_0.VALUES;
      sa[1] = kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_1.VALUES;
      sa[2] = kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_2.VALUES;
      sa[3] = kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_3.VALUES;
      sa[4] = kmeans_26607a20_9e61_407b_bb37_7f529ec5d76d_CENTERS_0_4.VALUES;
    }
  }
}

