package ap.hackathon.augmentedprivacy.ml;/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2018-03-22T02:09:05.197+01:00
  3.16.0.2
  
  Standalone prediction code with sample test data for KMeansModel named kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://10.1.3.192:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://10.1.3.192:54321/3/Models.java/kmeans-8fac4864-63c2-4bf4-a193-a2a32c0013e4 > kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;
import hex.genmodel.IClusteringModel;

@ModelPojo(name="kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4", algorithm="kmeans")
public class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4 extends GenModel implements IClusteringModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Clustering; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* BABY_ARTIKELEN */ null,
    /* BELASTINGEN */ null,
    /* ELEKTRONICA_WINKELS */ null,
    /* FAMILIELEDEN */ null,
    /* GOEDE_DOELEN */ null,
    /* HORECA */ null,
    /* HUUR */ null,
    /* HYPOTHEEKAFSCHRIJVINGEN */ null,
    /* LEESMATERIAAL */ null,
    /* MODEWINKELS */ null,
    /* NUTSBEDRIJVEN */ null,
    /* SPAREN */ null,
    /* SPORT_ARTIKELEN */ null,
    /* SUPERMARKTEN */ null,
    /* TANKEN */ null,
    /* TELECOMBEDRIJVEN */ null
  };

  public double[][]getKMeans() {
    return kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS.VALUES;
  }

  public kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4() { super(NAMES,DOMAINS,null); }
  public String getUUID() { return Long.toString(-7384670716645938832L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    Kmeans_preprocessData(data,kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MEANS.VALUES,kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MULTS.VALUES,kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MODES.VALUES);
    preds[0] = KMeans_closest(kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS.VALUES, data, DOMAINS); 
    return preds;
  }

  // Pass in data in a double[], in a same way as to the score0 function.
  // Cluster distances will be stored into the distances[] array. Function
  // will return the closest cluster. This way the caller can avoid to call
  // score0(..) to retrieve the cluster where the data point belongs.
  public final int distances( double[] data, double[] distances ) {
    Kmeans_preprocessData(data,kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MEANS.VALUES,kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MULTS.VALUES,kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MODES.VALUES);
    int cluster = KMeans_distances(kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS.VALUES, data, DOMAINS, distances); 
    return cluster;
  }

  // Returns number of cluster used by this model.
  public final int getNumClusters() {
    int nclusters = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS.VALUES.length;
    return nclusters;
  }
}
// The class representing training column names
class NamesHolder_kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4 implements java.io.Serializable {
  public static final String[] VALUES = new String[16];
  static {
    NamesHolder_kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_0.fill(VALUES);
  }
  static final class NamesHolder_kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "BABY_ARTIKELEN";
      sa[1] = "BELASTINGEN";
      sa[2] = "ELEKTRONICA_WINKELS";
      sa[3] = "FAMILIELEDEN";
      sa[4] = "GOEDE_DOELEN";
      sa[5] = "HORECA";
      sa[6] = "HUUR";
      sa[7] = "HYPOTHEEKAFSCHRIJVINGEN";
      sa[8] = "LEESMATERIAAL";
      sa[9] = "MODEWINKELS";
      sa[10] = "NUTSBEDRIJVEN";
      sa[11] = "SPAREN";
      sa[12] = "SPORT_ARTIKELEN";
      sa[13] = "SUPERMARKTEN";
      sa[14] = "TANKEN";
      sa[15] = "TELECOMBEDRIJVEN";
    }
  }
}
// Column means of training data
class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MEANS implements java.io.Serializable {
  public static final double[] VALUES = new double[16];
  static {
    kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MEANS_0.fill(VALUES);
  }
  static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MEANS_0 implements java.io.Serializable {
    static final void fill(double[] sa) {
      sa[0] = 1046.3009999999997;
      sa[1] = 302168.7201999998;
      sa[2] = 37566.24999999999;
      sa[3] = 32418.991799999996;
      sa[4] = 147.78249999999997;
      sa[5] = 1355.7687000000003;
      sa[6] = 10886.9967;
      sa[7] = 9654.824499999997;
      sa[8] = 121.65099999999998;
      sa[9] = 30215.482099999994;
      sa[10] = 931.7821999999999;
      sa[11] = 2965.4817999999987;
      sa[12] = 679.3291999999999;
      sa[13] = 3213.1558999999997;
      sa[14] = 699.1039;
      sa[15] = 269.8364000000002;
    }
  }
}
// Reciprocal of column standard deviations of training data
class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MULTS implements java.io.Serializable {
  public static final double[] VALUES = new double[16];
  static {
    kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MULTS_0.fill(VALUES);
  }
  static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MULTS_0 implements java.io.Serializable {
    static final void fill(double[] sa) {
      sa[0] = 9.81633893815109E-4;
      sa[1] = 3.222786441521775E-6;
      sa[2] = 2.2010000495399766E-5;
      sa[3] = 2.81615167202177E-5;
      sa[4] = 0.006534166837396137;
      sa[5] = 7.525065061107547E-4;
      sa[6] = 8.205251775296399E-5;
      sa[7] = 9.356637204138308E-5;
      sa[8] = 0.007354922377528845;
      sa[9] = 3.333457855910122E-5;
      sa[10] = 9.277748451251877E-4;
      sa[11] = 3.069971031621734E-4;
      sa[12] = 0.001504826525934068;
      sa[13] = 3.1483959282907665E-4;
      sa[14] = 0.0013764514333066457;
      sa[15] = 0.003408014821004887;
    }
  }
}
// Mode for categorical columns
class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MODES implements java.io.Serializable {
  public static final int[] VALUES = new int[16];
  static {
    kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MODES_0.fill(VALUES);
  }
  static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_MODES_0 implements java.io.Serializable {
    static final void fill(int[] sa) {
      sa[0] = -1;
      sa[1] = -1;
      sa[2] = -1;
      sa[3] = -1;
      sa[4] = -1;
      sa[5] = -1;
      sa[6] = -1;
      sa[7] = -1;
      sa[8] = -1;
      sa[9] = -1;
      sa[10] = -1;
      sa[11] = -1;
      sa[12] = -1;
      sa[13] = -1;
      sa[14] = -1;
      sa[15] = -1;
    }
  }
}
// Normalized cluster centers[K][features]
class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS implements java.io.Serializable {
  public static final double[][] VALUES = new double[16][];
  static {
    kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0.fill(VALUES);
  }
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_0 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_0_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_0_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.41534290311427224;
        sa[1] = 2.462021021288248;
        sa[2] = -0.5713220409878534;
        sa[3] = -0.10395973796998781;
        sa[4] = -0.4602457093470635;
        sa[5] = -0.3102488541366509;
        sa[6] = -0.1139513354349452;
        sa[7] = 0.38805033437596126;
        sa[8] = -0.352623347765046;
        sa[9] = 0.6539895505027701;
        sa[10] = -0.27935902314976085;
        sa[11] = -0.3326626135813164;
        sa[12] = -0.2687866106967625;
        sa[13] = -0.42955415557164217;
        sa[14] = 0.742417140499587;
        sa[15] = -0.21187374975372172;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_1 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_1_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_1_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = 2.607287354711603;
        sa[1] = -0.1441001285256756;
        sa[2] = -0.5021229453017529;
        sa[3] = -0.33575319925102065;
        sa[4] = -0.5692076086226707;
        sa[5] = 5.1163679639560895;
        sa[6] = -0.691165009892896;
        sa[7] = -0.582929211167415;
        sa[8] = -0.5312533982512858;
        sa[9] = 0.14307960812611623;
        sa[10] = -0.5183776803214554;
        sa[11] = -0.340180972637758;
        sa[12] = -0.2420049980394959;
        sa[13] = -0.4454935846148845;
        sa[14] = -0.5422997038547421;
        sa[15] = -0.8120154225474795;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_2 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_2_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_2_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.7421554707138684;
        sa[1] = -0.6679106146819075;
        sa[2] = 1.3448920270707487;
        sa[3] = 0.44140539288054914;
        sa[4] = -0.36962148257440575;
        sa[5] = -0.5659328272597269;
        sa[6] = 3.4776678235424043;
        sa[7] = -0.609622293615241;
        sa[8] = -0.45182023657397435;
        sa[9] = 0.13754140124430717;
        sa[10] = -0.5755796383976488;
        sa[11] = -0.3798772330621428;
        sa[12] = -0.4486853972439105;
        sa[13] = 0.08210830825622562;
        sa[14] = -0.5385832849848141;
        sa[15] = -0.7183631752662651;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_3 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_3_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_3_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = 0.8751918949901086;
        sa[1] = -0.4182316242991283;
        sa[2] = -0.3982185751630795;
        sa[3] = 0.05359413177951633;
        sa[4] = 3.1938027376166715;
        sa[5] = -0.27502509959490096;
        sa[6] = -0.4643808766006563;
        sa[7] = -0.4921057373224252;
        sa[8] = -0.5290653088439711;
        sa[9] = -0.28756714551262763;
        sa[10] = 0.5926141412190545;
        sa[11] = 0.14125418701943604;
        sa[12] = -0.6233581362417073;
        sa[13] = -0.288667260832829;
        sa[14] = -0.17196544572358904;
        sa[15] = -0.33740675853728636;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_4 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_4_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_4_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.08121155366921748;
        sa[1] = -0.41069583737124377;
        sa[2] = -0.2637147529245645;
        sa[3] = 0.8521937919264779;
        sa[4] = -0.11111169202357739;
        sa[5] = -0.4918807522892179;
        sa[6] = -0.22404184971455532;
        sa[7] = 0.36554343369097425;
        sa[8] = -0.25114526557108735;
        sa[9] = -0.4475350100614943;
        sa[10] = -0.5862217313017042;
        sa[11] = -0.09814684425994732;
        sa[12] = -0.19960567465656695;
        sa[13] = 2.2496221847315434;
        sa[14] = -0.48215030560972305;
        sa[15] = 0.2173148672068954;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_5 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_5_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_5_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.38159152517664074;
        sa[1] = -0.12329182113161731;
        sa[2] = -0.29881657072574525;
        sa[3] = -0.40013746685261836;
        sa[4] = -0.16951262317914906;
        sa[5] = -0.7105156648113169;
        sa[6] = -0.6788801069349221;
        sa[7] = -0.6359308182739769;
        sa[8] = -0.22977512999637853;
        sa[9] = -0.7678440864390894;
        sa[10] = 3.8286185790280993;
        sa[11] = 0.23404175897192928;
        sa[12] = -0.457345673900661;
        sa[13] = -0.9615880903680918;
        sa[14] = -0.20056810650770118;
        sa[15] = 2.9086506781363957;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_6 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_6_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_6_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.3933111431644668;
        sa[1] = 0.47875782713189063;
        sa[2] = -0.20636463968928717;
        sa[3] = -0.37892984216555;
        sa[4] = -0.5073217884871545;
        sa[5] = -0.2974297266368385;
        sa[6] = -0.4305735070666159;
        sa[7] = 0.7560049489689632;
        sa[8] = -0.4753723324540167;
        sa[9] = 0.07999139959041496;
        sa[10] = -0.1350973980252158;
        sa[11] = -0.32831280573740074;
        sa[12] = 2.472534851798237;
        sa[13] = -0.09589605055924763;
        sa[14] = -0.12510033320046066;
        sa[15] = -0.3492183699044192;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_7 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_7_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_7_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = 1.868944059224365;
        sa[1] = -0.034429656642689856;
        sa[2] = -0.32341610280443006;
        sa[3] = 0.13424072483585042;
        sa[4] = -0.6757798697406018;
        sa[5] = -0.1495088956418923;
        sa[6] = -0.41054334786481517;
        sa[7] = 0.9666817212765261;
        sa[8] = -0.31709644592358976;
        sa[9] = -0.1267821809962388;
        sa[10] = -0.4009747319822013;
        sa[11] = -0.08616351080741769;
        sa[12] = -0.202973560023081;
        sa[13] = -0.2001296447354002;
        sa[14] = -0.2284670564965352;
        sa[15] = 0.2313184947734829;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_8 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_8_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_8_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.23885017740919814;
        sa[1] = 0.10986767461504797;
        sa[2] = 0.2698022837526937;
        sa[3] = -0.546980007163816;
        sa[4] = 0.1443974639118112;
        sa[5] = -0.1040942500738511;
        sa[6] = -0.36915531943756036;
        sa[7] = -0.263108684963555;
        sa[8] = 2.009381955026428;
        sa[9] = -0.31845625494252855;
        sa[10] = 0.3420320518157559;
        sa[11] = -0.39184838043521636;
        sa[12] = -0.25949208548853364;
        sa[13] = -0.2200109254503088;
        sa[14] = -0.31769494713920804;
        sa[15] = -0.46511132190751137;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_9 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_9_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_9_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.4864987394086615;
        sa[1] = -0.5305390525612621;
        sa[2] = -0.4127390677149059;
        sa[3] = -0.1824606061668439;
        sa[4] = -0.0549523431025013;
        sa[5] = 0.3220900671814931;
        sa[6] = 0.5245907351492209;
        sa[7] = -0.4656303526335488;
        sa[8] = -0.15741495200545721;
        sa[9] = 1.427410223670061;
        sa[10] = 0.07020886659159796;
        sa[11] = -0.4794896064488505;
        sa[12] = -0.1541971162291381;
        sa[13] = -0.5232041294812487;
        sa[14] = -0.35941633712559357;
        sa[15] = 1.4101976815628623;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_10 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_10_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_10_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.4125326255096931;
        sa[1] = -0.3615566365465944;
        sa[2] = 0.3694634449408611;
        sa[3] = 1.0461491823125104;
        sa[4] = -0.35005165289640433;
        sa[5] = 0.7395474410677197;
        sa[6] = -0.5987915161943753;
        sa[7] = -0.5116966643004499;
        sa[8] = -0.4543760721001656;
        sa[9] = -0.7169811030998097;
        sa[10] = 0.25174038537160937;
        sa[11] = -0.4470566416543633;
        sa[12] = -0.5696132568679722;
        sa[13] = -0.26607122325548627;
        sa[14] = 3.007984919201672;
        sa[15] = -0.22549607185253842;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_11 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_11_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_11_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.3744501385991359;
        sa[1] = -0.42968339575642617;
        sa[2] = 2.92919167173007;
        sa[3] = -0.5210933402155687;
        sa[4] = -0.23350389707338193;
        sa[5] = -0.19383591847310142;
        sa[6] = -0.2898390343449438;
        sa[7] = -0.2502098432354647;
        sa[8] = -0.5270856089040196;
        sa[9] = 0.35436572302093355;
        sa[10] = 0.007941257861021048;
        sa[11] = -0.3632712480902623;
        sa[12] = -0.09780499619186382;
        sa[13] = 0.4860663962315006;
        sa[14] = -0.48020568561255716;
        sa[15] = -0.506964015919332;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_12 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_12_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_12_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.7122499941387912;
        sa[1] = -0.3601209254717269;
        sa[2] = -0.47317847405027247;
        sa[3] = 0.592645832773393;
        sa[4] = 1.6741352208263578;
        sa[5] = 1.8803115602725837;
        sa[6] = -0.5723045532011298;
        sa[7] = 0.8453249671592017;
        sa[8] = -0.640290122498151;
        sa[9] = -0.19377630858716932;
        sa[10] = -0.39400946233242384;
        sa[11] = -0.25682204921613305;
        sa[12] = -0.6303856761178195;
        sa[13] = -0.08181764834412561;
        sa[14] = -0.058614670190786824;
        sa[15] = 0.31412899490537544;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_13 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_13_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_13_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.05519825548311713;
        sa[1] = -0.3895431568939305;
        sa[2] = -0.4925080416603412;
        sa[3] = 0.5165987898391803;
        sa[4] = -0.0527633972119736;
        sa[5] = -0.06403262224590432;
        sa[6] = 1.171643043786724;
        sa[7] = -0.11417268128880069;
        sa[8] = -0.4133539925394985;
        sa[9] = -0.2648227542206369;
        sa[10] = 0.9553543904475439;
        sa[11] = -0.16225159158702557;
        sa[12] = -0.17081541716386994;
        sa[13] = -0.523351841723551;
        sa[14] = 0.2633218349810129;
        sa[15] = -0.3400011098197763;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_14 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_14_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_14_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = 1.9161091137374466;
        sa[1] = -0.49802476300105414;
        sa[2] = -0.6262592380458051;
        sa[3] = -0.44413026181227366;
        sa[4] = -0.43476712594324524;
        sa[5] = -0.38695667984634513;
        sa[6] = 0.7158440769414833;
        sa[7] = -0.5317666511033265;
        sa[8] = -0.4606829180388966;
        sa[9] = -0.7248149790705376;
        sa[10] = -0.5935877481415286;
        sa[11] = -0.3442486842546568;
        sa[12] = -0.7264011326050427;
        sa[13] = 0.21499737779548644;
        sa[14] = 2.054403454106911;
        sa[15] = 1.2277496081203656;
      }
    }
}
  static class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_15 implements java.io.Serializable {
    public static final double[] VALUES = new double[16];
    static {
      kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_15_0.fill(VALUES);
    }
    static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_15_0 implements java.io.Serializable {
      static final void fill(double[] sa) {
        sa[0] = -0.06641636762163618;
        sa[1] = -0.07197110631729889;
        sa[2] = -0.14869020909671013;
        sa[3] = -0.006051059465369773;
        sa[4] = 0.2134679634943133;
        sa[5] = 0.17244311167927986;
        sa[6] = -0.003800483901526474;
        sa[7] = -0.27687089479526183;
        sa[8] = -0.2438230317374585;
        sa[9] = -0.6410410829983535;
        sa[10] = -0.5569591972559863;
        sa[11] = 2.525656940192836;
        sa[12] = -0.017278719136080024;
        sa[13] = -0.07311296328158731;
        sa[14] = -0.1566469177223194;
        sa[15] = -0.48562643512502046;
      }
    }
}
  static final class kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0 implements java.io.Serializable {
    static final void fill(double[][] sa) {
      sa[0] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_0.VALUES;
      sa[1] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_1.VALUES;
      sa[2] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_2.VALUES;
      sa[3] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_3.VALUES;
      sa[4] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_4.VALUES;
      sa[5] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_5.VALUES;
      sa[6] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_6.VALUES;
      sa[7] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_7.VALUES;
      sa[8] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_8.VALUES;
      sa[9] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_9.VALUES;
      sa[10] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_10.VALUES;
      sa[11] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_11.VALUES;
      sa[12] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_12.VALUES;
      sa[13] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_13.VALUES;
      sa[14] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_14.VALUES;
      sa[15] = kmeans_8fac4864_63c2_4bf4_a193_a2a32c0013e4_CENTERS_0_15.VALUES;
    }
  }
}

